kind: "Template"
apiVersion: "v1"
labels:
  name : "nats-server"
metadata:
  name: nats-server
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${NAME}
  spec:
    tags:
    - name: from
      from:
        kind: DockerImage
        name: golang
      importPolicy:
        scheduled: true        
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${NAME}
  spec:
    successfulBuildsHistoryLimit: 2
    failedBuildsHistoryLimit: 1
    triggers:
    - type: ConfigChange
    - type: ImageChange
    source:
      type: Git
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      sourceSecret:
        name: githubcredential
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: ${NAME}:from
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    nodeSelector: null        
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${NAME}
  spec:
    revisionHistoryLimit: 2
    strategy:
      resources: {}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: ${NAME}:latest
    replicas: 1
    test: false
    selector:
      deploymentconfig: ${NAME}
    template:
      metadata:
        labels:
          deploymentconfig: ${NAME}
        annotations:
          vaultproject.io/policies: default,secret_readonly,nats-server
          vaultproject.io/ttl: "24h"
      spec:
        
        containers:
        - name: ${NAME}
          image: ${NAME}           
- kind: Service
  apiVersion: v1
  metadata:
    name: ${NAME}
  spec:
    ports:
    - name: 4222-tcp
      port: 4222
      targetPort: 4222
    selector:
      deploymentconfig: ${NAME}

parameters:
- name: NAME
  description: The name assigned to all of the objects defined in this template.
  required: true
  value: message-bus
- name: SOURCE_REPOSITORY_URL
  displayName: Git Repository URL
  description: The URL of the repository with your application source code.
  required: true
  value: https://github.com/ckhungaa/message-bus.git
- name: SOURCE_REPOSITORY_REF
  displayName: Git Reference
  description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch.
  required: true
  value: master
  